//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvitoParser.Data.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisment
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Url { get; set; }
        public Nullable<long> Number { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public string Seller { get; set; }
        public Nullable<System.DateTime> DatePublished { get; set; }
        public string Text { get; set; }
        public string Type { get; set; }
        public Nullable<bool> SoldOut { get; set; }
        public Nullable<System.DateTime> DateSold { get; set; }
    }
}
